### PR TITLE
Support Sign in with Slack tokens

### PR DESCRIPTION
**Pull request by ibash**
If you use "Sign in with Slack" then the token recieved can't access the
"auth.test" endpoint. Instead the identity needs to be fetched from the
"users.identity" endpoint.

This change makes the slack strategy fetch the identity in addition to
the auth wheth the "identity.basic" scope is present.

Note that the strategy always attempts to fetch the auth because
sometimes the token can access _both_ endpoints (say if the scope has
"users:read" _and_ "identity.basic"). The difference is that if the
"identity.basic" scope is present we don't consider an "invalid_auth"
response from the "auth.test" endpoint to be an error case.

ref: https://api.slack.com/docs/sign-in-with-slack

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @ibash! Sorry for the delay in getting to your PR.

@ueberauth/developers any thoughts on this, I think we're good to merge but I'd like to give you a quick chance to offer thoughts.

**Review by yordis — APPROVED** [review]

**Comment by doomspork** [comment]
Thank you @yordis and @ibash 🎉

**Comment by doomspork** [comment]
@ibash we're always looking for contributors if you're interested in helping improve Ueberauth and it's strategies 😁

**Comment by ibash** [comment]
I'm always open to submitting pull requests :)

**Comment by doomspork** [comment]
@ibash any where you think we can improve the code either through features or refactors, please do. I think we can do a lot to make the projects themselves more approachable which itself encourage more contributors 😁

**Pull request merged**
