### PR TITLE
updated oauth2 dependency to ~> 0.8.0

### PR DESCRIPTION
**Pull request by zkwentz**

### CODE REVIEW

**Comment by zkwentz** [comment]
Fix for #15

**Comment by nickcampbell18** [comment]
This is really helpful, thanks! What would it take to get this merged?

**Review by hassox — CHANGES_REQUESTED** [review]
This one needs a rebase. Other than that LGTM

**Comment by doomspork** [comment]
@zkwentz could you rebase please?  😁

**Comment by zkwentz** [comment]
Will do @doomspork

**Comment by zkwentz** [comment]
FYI rebased, thanks for your review!

CC \ @doomspork @hassox @nickcampbell18

**Comment by yordis** [comment]
@zkwentz notice that there is a merge conflict still in the status of the PR Github show you that.

**Comment by zkwentz** [comment]
@yordis I think that's based on @hassox's review prior to the rebase.

**Comment by zkwentz** [comment]
@yordis apologies, I see now, new computer, didn't have upstream.

Resolving now.

**Comment by zkwentz** [comment]
Updated.

Not sure what travis is doing, don't recall seeing it prior to rebase changes made today.

**Comment by doomspork** [comment]
Don't worry about @zkwentz, configuration issue 👍

**Pull request merged**
